//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.info

import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass
import kotlinx.serialization.*

data class ExternalNameMirror(
    val name: String
): MirrorAnnotation {
    override val annotationType: KClass<out Annotation> get() = ExternalName::class
    override fun asMap(): Map<String, Any?> = mapOf(
        "name" to name
    )
}
