//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.test

import kotlinx.serialization.Serializable
import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass

@Suppress("RemoveExplicitTypeArguments", "UNCHECKED_CAST", "USELESS_CAST")
object AttitudeClassInfo: ClassInfo<Attitude> {

    override val kClass: KClass<Attitude> = Attitude::class
    override val modifiers: List<ClassInfo.Modifier> = listOf()
    override val companion: Any? get() = null

    override val implements: List<Type<*>> = listOf()

    override val packageName: String = "com.lightningkite.mirror.test"
    override val owner: KClass<*>? = null
    override val ownerName: String? = null

    override val name: String = "Attitude"
    override val annotations: List<AnnotationInfo> = listOf()
    override val enumValues: List<Attitude>? = listOf(Attitude.POSITIVE, Attitude.NEUTRAL, Attitude.NEGATIVE)

    

    override val fields:List<FieldInfo<Attitude, *>> = listOf()

    override fun construct(map: Map<String, Any?>): Attitude = throw NotImplementedError()

}