//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.test

import kotlinx.serialization.Serializable
import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass
import kotlinx.serialization.*
import mirror.kotlin.*

object AttitudeMirror : MirrorEnum<Attitude>() {
    @Suppress("UNCHECKED_CAST")
    override val kClass: KClass<Attitude> get() = Attitude::class as KClass<Attitude>
    override val modifiers: Array<Modifier> get() = arrayOf()
    override val packageName: String get() = "com.lightningkite.mirror.test"
    override val localName: String get() = "Attitude"
    override val enumValues: Array<Attitude> get() = arrayOf(Attitude.POSITIVE,Attitude.NEUTRAL,Attitude.NEGATIVE)
}
