//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.test

import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass
import kotlinx.serialization.*
import mirror.kotlin.*

object SatisfiesExampleAnyTestMirror : MirrorObject<SatisfiesExample.AnyTest>(SatisfiesExample.AnyTest) {
    @Suppress("UNCHECKED_CAST")
    override val kClass: KClass<SatisfiesExample.AnyTest> get() = SatisfiesExample.AnyTest::class as KClass<SatisfiesExample.AnyTest>
    override val modifiers: Array<Modifier> get() = arrayOf(Modifier.Object)
    override val packageName: String get() = "com.lightningkite.mirror.test"
    override val localName: String get() = "SatisfiesExample.AnyTest"
    override val implements: Array<MirrorClass<*>> get() = arrayOf(SatisfiesExampleMirror(AnyMirror.nullable))
    override val owningClass: KClass<*>? get() = SatisfiesExample::class
    
}
