//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package kotlinx.serialization

import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass
import kotlinx.serialization.*

data class SerializableMirror(
    val with: kotlin.reflect.KClass<out kotlinx.serialization.KSerializer<*>> = KSerializer::class
): MirrorAnnotation {
    override val annotationType: KClass<out Annotation> get() = Serializable::class
    override fun asMap(): Map<String, Any?> = mapOf(
        "with" to with
    )
}
