//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.serialization.json

import com.lightningkite.mirror.registerTest
import com.lightningkite.recktangle.Point
import com.lightningkite.recktangle.PointMirror
import kotlinx.serialization.json.Json
import kotlin.reflect.KClass
import kotlin.test.Test
import com.lightningkite.mirror.info.*
import kotlinx.serialization.*

object SimpleJSONTestTestEnumMirror : MirrorEnum<SimpleJSONTest.TestEnum>() {
    @Suppress("UNCHECKED_CAST")
    override val kClass: KClass<SimpleJSONTest.TestEnum> get() = SimpleJSONTest.TestEnum::class as KClass<SimpleJSONTest.TestEnum>
    override val modifiers: Array<Modifier> get() = arrayOf()
    override val packageName: String get() = "com.lightningkite.mirror.serialization.json"
    override val localName: String get() = "SimpleJSONTest.TestEnum"
    override val enumValues: Array<SimpleJSONTest.TestEnum> get() = arrayOf(SimpleJSONTest.TestEnum.ValueA,SimpleJSONTest.TestEnum.ValueB,SimpleJSONTest.TestEnum.ValueC)
    override val owningClass: KClass<*>? get() = SimpleJSONTest::class
}
