//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.info

import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass
import kotlinx.serialization.*

object TestParentMirror : MirrorClass<TestParent>() {
    @Suppress("UNCHECKED_CAST")
    override val kClass: KClass<TestParent> get() = TestParent::class as KClass<TestParent>
    override val modifiers: Array<Modifier> get() = arrayOf(Modifier.Open)
    override val packageName: String get() = "com.lightningkite.mirror.info"
    override val localName: String get() = "TestParent"
    
    override val fields: Array<Field<TestParent, *>> = arrayOf()
    
    override fun deserialize(decoder: Decoder): TestParent {
        val decoderStructure = decoder.beginStructure(this)
        loop@ while (true) {
            when (decoderStructure.decodeElementIndex(this)) {
                CompositeDecoder.READ_ALL -> {
                }
                CompositeDecoder.READ_DONE -> break@loop
                else -> {}
            }
        }
        decoderStructure.endStructure(this)
        return TestParent(
        )
    }
    
    override fun serialize(encoder: Encoder, obj: TestParent) {
        val encoderStructure = encoder.beginStructure(this)
        encoderStructure.endStructure(this)
    }
}
