//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.info


import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass

@Suppress("RemoveExplicitTypeArguments", "UNCHECKED_CAST", "USELESS_CAST")
object TestChildClassInfo: ClassInfo<TestChild> {

   override val kClass: KClass<TestChild> = TestChild::class
   override val modifiers: List<ClassInfo.Modifier> = listOf()

   override val implements: List<Type<*>> = listOf(Type<TestParent>(TestParent::class, listOf(), false), Type<TestAnotherInterface>(TestAnotherInterface::class, listOf(), false))

   override val packageName: String = "com.lightningkite.mirror.info"
   override val owner: KClass<*>? = null
   override val ownerName: String? = null

   override val name: String = "TestChild"
   override val annotations: List<AnnotationInfo> = listOf()
   override val enumValues: List<TestChild>? = null

   object Fields {
       
   }

   override val fields:List<FieldInfo<TestChild, *>> = listOf()

   override fun construct(map: Map<String, Any?>): TestChild {
       //Gather variables
       
           //Handle the optionals
       
       //Finally do the call
       return TestChild(
           
       )
   }

}