//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.info

import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass
import kotlinx.serialization.*

object TestAnotherInterfaceMirror : PolymorphicMirror<TestAnotherInterface>() {
    @Suppress("UNCHECKED_CAST")
    override val kClass: KClass<TestAnotherInterface> get() = TestAnotherInterface::class as KClass<TestAnotherInterface>
    override val modifiers: Array<Modifier> get() = arrayOf(Modifier.Interface)
    override val packageName: String get() = "com.lightningkite.mirror.info"
    override val localName: String get() = "TestAnotherInterface"
}
