//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package test

import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass
import kotlinx.serialization.*

data class CustomAnnotationMirror(
    val x: Int = 0
): MirrorAnnotation {
    override val annotationType: KClass<out Annotation> get() = CustomAnnotation::class
    override fun asMap(): Map<String, Any?> = mapOf(
        "x" to x
    )
}
